# Travis CI configuration for remote testing.
# See:
#   https://docs.travis-ci.com/user/customizing-the-build/
#   https://docs.travis-ci.com/user/languages/python

language: python

python:
  - "pypy3"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"

sudo: false

install:
 - pip install coverage

script:
 - coverage run --source=giog -m unittest discover -s tests

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
#- pyflakes giog/*.py | tee >(wc -l)
 - pep8 --statistics --count giog
